# Generated by Django 6.0.3 on 2026-03-25 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0005_alter_reviewrating_subject_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='shop',
            field=models.ForeignKey(default='test@example.com', on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='accounts.shopownerprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='birth_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
