# Generated by Django 6.0.3 on 2026-03-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_shopownerprofile_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopownerprofile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
