# Generated by Django 6.0.3 on 2026-03-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopowner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shopowner',
            name='created_at',
        ),
        migrations.AddField(
            model_name='shopowner',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
