# Generated by Django 6.0.3 on 2026-03-27 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_shopownerprofile_qr_code'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='message',
            new_name='message_body',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='scheduled_time',
            new_name='scheduled_for',
        ),
        migrations.AddField(
            model_name='campaign',
            name='delivered_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='failed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='template_type',
            field=models.CharField(choices=[('custom', 'Custom'), ('new_arrivals', 'New Arrivals'), ('sale_alert', 'Sale Alert'), ('birthday_offer', 'Birthday Offer')], default='custom', max_length=30),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_recipients',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='accounts.shopownerprofile'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('scheduled', 'Scheduled')], default='draft', max_length=20),
        ),
    ]
