# Generated by Django 6.0.3 on 2026-03-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_rename_message_campaign_message_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent')], default='draft', max_length=20),
        ),
    ]
